---
driver:
  name: docker
  socket: <%= ENV['DOCKER_HOST'] %>

provisioner:
  name: chef_solo
  encrypted_data_bag_secret_key_path: ../../.chef_databag_secret
  data_bags_path: ../../data_bags
  roles_path: ../../roles

platforms:
  - name: ubuntu-12.04
    driver_config:
      image: kazu634:ubuntu1204
  - name: ubuntu-14.04
    driver_config:
      image: kazu634:ubuntu1404

suites:
  - name: default
    run_list:
      - recipe[kazu634::default]
    attributes: { kazu634: { ruby_support: false },
                  base: { ssh: false }}
