site :opscode

metadata
cookbook 'td-agent', git: 'https://github.com/treasure-data/chef-td-agent.git'
cookbook 'monit', path: '../monit'
cookbook 'base', path: '../base'
cookbook 'consul', path: '../consul'
