source 'https://api.berkshelf.com'

cookbook 'apt'
cookbook 'build-essential'
cookbook 'iptables'
cookbook 'sensu'
cookbook 'uchiwa'
cookbook 'td-agent', git: 'https://github.com/treasure-data/chef-td-agent.git'
cookbook 'omnibus_updater', git: 'https://github.com/hw-cookbooks/omnibus_updater'
cookbook 'chef_handler'
