source 'https://rubygems.org'
gem 'chef'
gem 'knife-solo'
gem 'berkshelf'
gem 'knife-ec2'
gem 'knife-solo_data_bag'
gem 'foodcritic', "~> 3.0.0"
gem 'serverspec'
gem 'ci_reporter'
gem 'test-kitchen', :git => 'https://github.com/test-kitchen/test-kitchen'
gem 'kitchen-vagrant'
gem 'kitchen-docker', :git => 'https://github.com/peterabbott/kitchen-docker.git'
