source 'https://rubygems.org'
gem 'chef'
gem 'knife-solo'
gem 'berkshelf'
gem 'knife-ec2'
gem 'knife-solo_data_bag'
gem 'foodcritic', '~> 3.0.0'
gem 'rubocop'
gem 'serverspec'
gem 'ci_reporter'
gem 'test-kitchen', git: 'https://github.com/test-kitchen/test-kitchen'
gem 'kitchen-vagrant'
gem 'kitchen-docker', '~> 2.1.0'
