---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  encrypted_data_bag_secret_key_path: ../../.chef_databag_secret
  data_bags_path: ../../data_bags
  roles_path: ../../roles


platforms:
  - name: ubuntu-12.04
    driver:
      box: ubuntu-1204x64
  - name: ubuntu-14.04
    driver:
      box: ubuntu-1404x64

suites:
  - name: default
    run_list:
      - recipe[webapp::default]
    attributes: { nginx: { iptables: false },
                  base: { ssh: false },
                  ruby: { install: false }}
