#!/bin/bash

USER="growth"
HOME="/var/lib/growthforecast"

source $HOME/perl5/perlbrew/etc/bashrc

PERLBREW="${HOME}/perl5/perlbrew/bin/perlbrew"
PERL=`${PERLBREW}  list | grep \* | cut -f 2 -d " "`
GROWTHFORECAST=`find ${HOME}/perl5 -type f -name "growthforecast.pl" | grep bin | grep ${PERL}`

PID_FILE="/var/run/growthforecast.pid"
LOG_FILE="/var/log/growthforecast/growthforecast.log"

start() {
  su - ${USER} -c "${PERLBREW} exec perl ${GROWTHFORECAST} --port=5125 \
                                                           --data-dir ${HOME}/appdata \
                                                           --host 127.0.0.1 \
                                                           --front-proxy 0.0.0.0 \
                                    >>$LOG_FILE 2>&1 &"

  echo `pgrep -o -f 'growthforecast.pl'` >> ${PID_FILE}
}

stop() {
  if [ -e $PID_FILE ]; then
    kill `cat $PID_FILE`

    rm -f $PID_FILE
  fi

  pkill -u growth perl
}

usage() {
  echo "Usage: `basename $0`  {start|stop|restart}"
}

case $1 in
  start)
    start
  ;;
  stop)
    stop
  ;;
  restart)
    stop
    start
  ;;
  *)
    usage
  ;;
esac
